<?php if (!$block->getLoadedProductCollection()->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $block->getMode(); ?> products-<?php /* @escapeNotVerified */ echo $block->getMode(); ?>">
        <ol class="products list items product-`items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php echo $block->renderProducts(); ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
